version: '3'

services:
  nginx:
    image: nginx:alpine
    networks:
      - tic-tac-toe-api
    ports:
      - "${APP_PORT:-80}:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    depends_on:
      - app
      - mysql

  mysql:
    image: mysql
    networks:
      - tic-tac-toe-api
    ports:
      - '${FORWARD_DB_PORT:-3306}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - mysql:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    ports:
      - '${FORWARD_PHPMYADMIN_PORT:-8080}:80'
    environment:
      PMA_HOST: 'mysql'
    networks:
      - tic-tac-toe-api
    depends_on:
      - mysql

  redis:
    image: redis:alpine
    ports:
      - '${FORWARD_REDIS_PORT:-6379}:6379'
    networks:
      - tic-tac-toe-api
    volumes:
      - redis:/data

  app:
    container_name: app
    build:
      args:
        user: bohdan
        uid: 1000
      context: .
      dockerfile: docker/api/Dockerfile
    networks:
      - tic-tac-toe-api
    ports:
      - '${PUSHER_PORT:-6001}:6001'
    volumes:
      - '.:/var/www'
    depends_on:
      - mysql
      - redis

volumes:
  mysql:
    driver: local
  redis:
    driver: local

networks:
  tic-tac-toe-api:
    driver: bridge
